In [2]:
import pandas as pd
import numpy as np

In [12]:
incorrectData = pd.read_csv("rawData_Surat_Tax.csv")

In [20]:
incorrectData.head(25)

,CityName,VehicleTypeId,Description,Year,Month,Count,Amount
0,Surat,1,"""MOTOR CYCLE""",1989.0,8,1.0,144.0
1,Surat,2,MOTOR CYCLE,1994.0,3,1.0,27.0
2,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,NaN,3,2.0,144.0
3,Surat,1,MOPED/SCOOTER,1997.0,4,NaN,21230.0
4,Surat,2,MOTOR CYCLE,1997.0,4,105.0,7022.0
5,Surat,3,AUTO RICKSHAW,1997.0,6,5.0,1294.0
6,Surat,9,LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON,1997.0,6,3.0,1050.0
7,Surat,21,TEMPO,1997.0,6,3.0,468.0
8,Surat,9,LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON,1997.0,7,1.0,180.0
9,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1997.0,8,56.0,5530.0
10,Surat,21,TEMPO,1997.0,8,2.0,108.0
11,Surat,1,MOPED/SCOOTER,1997.0,10,750.0,114669.0
12,Surat,3,AUTO RICKSHAW,1997.0,10,2.0,318.0
13,Surat,7,PUBLIC MOTOR CAR MORE THAN 16 SEAT,1997.0,11,1.0,360.0
14,Surat,5,PUBLIC MOTOR CAR 1 TO 6 SEAT,1997.0,12,9.0,3348.0
15,Surat,6,PUBLIC MOTOR CAR 7 TO 15 SEAT,1997.0,12,1.0,744.0
16,Surat,8,LOADING TRUCK/TEMPO/TRACTOR UPTO 2 TON,1997.0,12,1.0,684.0
17,Surat,1,MOPED/SCOOTER,1998.0,1,309.0,39575.3
18,Surat,10,LOADING TRUCK/TEMPO/TRACTOR 4 TO 8 TON,1998.0,1,3.0,780.0
19,Surat,1,MOPED/SCOOTER,1998.0,2,140.0,15983.0
20,Surat,2,MOTOR CYCLE,1998.0,2,38.0,4099.0
21,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1998.0,2,35.0,8185.0

In [ ]:
# Missing Values

In [22]:
incorrectData.VehicleTypeId.unique()

array([ 1,  2,  4,  3,  9, 21,  7,  5,  6,  8, 10], dtype=int64)

In [24]:
incorrectData.Year.unique()

array([1989., 1994.,   nan, 1997., 1998.])

In [26]:
incorrectData.Month.unique()

array([ 8,  3,  4,  6,  7, 10, 11, 12,  1,  2], dtype=int64)

In [28]:
incorrectData.head()

,CityName,VehicleTypeId,Description,Year,Month,Count,Amount
0,Surat,1,"""MOTOR CYCLE""",1989.0,8,1.0,144.0
1,Surat,2,MOTOR CYCLE,1994.0,3,1.0,27.0
2,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,NaN,3,2.0,144.0
3,Surat,1,MOPED/SCOOTER,1997.0,4,NaN,21230.0
4,Surat,2,MOTOR CYCLE,1997.0,4,105.0,7022.0

In [ ]:
## Quetions

In [30]:
#Sub Setting Data

In [ ]:
# Filtering Data

In [34]:
incorrectData.head(25)

,CityName,VehicleTypeId,Description,Year,Month,Count,Amount
0,Surat,1,"""MOTOR CYCLE""",1989.0,8,1.0,144.0
1,Surat,2,MOTOR CYCLE,1994.0,3,1.0,27.0
2,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,NaN,3,2.0,144.0
3,Surat,1,MOPED/SCOOTER,1997.0,4,NaN,21230.0
4,Surat,2,MOTOR CYCLE,1997.0,4,105.0,7022.0
5,Surat,3,AUTO RICKSHAW,1997.0,6,5.0,1294.0
6,Surat,9,LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON,1997.0,6,3.0,1050.0
7,Surat,21,TEMPO,1997.0,6,3.0,468.0
8,Surat,9,LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON,1997.0,7,1.0,180.0
9,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1997.0,8,56.0,5530.0
10,Surat,21,TEMPO,1997.0,8,2.0,108.0
11,Surat,1,MOPED/SCOOTER,1997.0,10,750.0,114669.0
12,Surat,3,AUTO RICKSHAW,1997.0,10,2.0,318.0
13,Surat,7,PUBLIC MOTOR CAR MORE THAN 16 SEAT,1997.0,11,1.0,360.0
14,Surat,5,PUBLIC MOTOR CAR 1 TO 6 SEAT,1997.0,12,9.0,3348.0
15,Surat,6,PUBLIC MOTOR CAR 7 TO 15 SEAT,1997.0,12,1.0,744.0
16,Surat,8,LOADING TRUCK/TEMPO/TRACTOR UPTO 2 TON,1997.0,12,1.0,684.0
17,Surat,1,MOPED/SCOOTER,1998.0,1,309.0,39575.3
18,Surat,10,LOADING TRUCK/TEMPO/TRACTOR 4 TO 8 TON,1998.0,1,3.0,780.0
19,Surat,1,MOPED/SCOOTER,1998.0,2,140.0,15983.0
20,Surat,2,MOTOR CYCLE,1998.0,2,38.0,4099.0
21,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1998.0,2,35.0,8185.0

In [32]:
# Iloc purely Interger based selection by position mechanism
# This line will select the 6th row of the data
incorrectData.iloc[5,:]

CityName                 Surat
VehicleTypeId                3
Description      AUTO RICKSHAW
Year                    1997.0
Month                        6
Count                      5.0
Amount                  1294.0
Name: 5, dtype: object

In [36]:
# this line will select the 3rd column of data
incorrectData.iloc[:, 2].head()

0                     "MOTOR CYCLE"
1    MOTOR CYCLE
2                       PRIVATE MOTOR CAR/JEEP CAR
3    MOPED/SCOOTER
4    MOTOR CYCLE
Name: Description, dtype: object

In [40]:
# this line will select the first 3 columns ofof the first 5 rows in the data
incorrectData.iloc[: 5, :3]

  CityName  VehicleTypeId                                    Description
0    Surat              1                   "MOTOR CYCLE"
1    Surat              2  MOTOR CYCLE
2    Surat              4                     PRIVATE MOTOR CAR/JEEP CAR
3    Surat              1  MOPED/SCOOTER
4    Surat              2  MOTOR CYCLE

In [48]:
incorrectData.loc[incorrectData['Year']== 1997]

,CityName,VehicleTypeId,Description,Year,Month,Count,Amount
3,Surat,1,MOPED/SCOOTER,1997.0,4,NaN,21230.0
4,Surat,2,MOTOR CYCLE,1997.0,4,105.0,7022.0
5,Surat,3,AUTO RICKSHAW,1997.0,6,5.0,1294.0
6,Surat,9,LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON,1997.0,6,3.0,1050.0
7,Surat,21,TEMPO,1997.0,6,3.0,468.0
8,Surat,9,LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON,1997.0,7,1.0,180.0
9,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1997.0,8,56.0,5530.0
10,Surat,21,TEMPO,1997.0,8,2.0,108.0
11,Surat,1,MOPED/SCOOTER,1997.0,10,750.0,114669.0
12,Surat,3,AUTO RICKSHAW,1997.0,10,2.0,318.0
13,Surat,7,PUBLIC MOTOR CAR MORE THAN 16 SEAT,1997.0,11,1.0,360.0
14,Surat,5,PUBLIC MOTOR CAR 1 TO 6 SEAT,1997.0,12,9.0,3348.0
15,Surat,6,PUBLIC MOTOR CAR 7 TO 15 SEAT,1997.0,12,1.0,744.0
16,Surat,8,LOADING TRUCK/TEMPO/TRACTOR UPTO 2 TON,1997.0,12,1.0,684.0

In [52]:
# The below line of code will select all rows where description is matched and year is 1997 
incorrectData.loc[(incorrectData['Year']== 1997)& (incorrectData['Description'].str.strip()== 'TEMPO')]

   CityName  VehicleTypeId Description    Year  Month  Count  Amount
7     Surat             21       TEMPO  1997.0      6    3.0   468.0
10    Surat             21       TEMPO  1997.0      8    2.0   108.0

In [58]:
# The below line of code will select all rows where description is matched and year is between given values,(:) no limit
incorrectData.loc[(incorrectData['Year']>=1989) & (incorrectData['Year']<= 1997) & (incorrectData['Description'].str.strip()== 'TEMPO'),:]

   CityName  VehicleTypeId Description    Year  Month  Count  Amount
7     Surat             21       TEMPO  1997.0      6    3.0   468.0
10    Surat             21       TEMPO  1997.0      8    2.0   108.0

In [72]:
incorrectData.filter(like='ption')

                                      Description
0                    "MOTOR CYCLE"
1   MOTOR CYCLE
2                      PRIVATE MOTOR CAR/JEEP CAR
3   MOPED/SCOOTER
4   MOTOR CYCLE
5                                   AUTO RICKSHAW
6   LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON
7                                           TEMPO
8   LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON
9                      PRIVATE MOTOR CAR/JEEP CAR
10                                          TEMPO
11  MOPED/SCOOTER
12                                  AUTO RICKSHAW
13             PUBLIC MOTOR CAR MORE THAN 16 SEAT
14                   PUBLIC MOTOR CAR 1 TO 6 SEAT
15                  PUBLIC MOTOR CAR 7 TO 15 SEAT
16  LOADING TRUCK/TEMPO/TRACTOR UPTO 2 TON
17  MOPED/SCOOTER
18  LOADING TRUCK/TEMPO/TRACTOR 4 TO 8 TON
19  MOPED/SCOOTER
20  MOTOR CYCLE
21                     PRIVATE MOTOR CAR/JEEP CAR

In [74]:
incorrectData.filter(like='on')

                                      Description  Month
0                    "MOTOR CYCLE"                     8
1   MOTOR CYCLE                                        3
2                      PRIVATE MOTOR CAR/JEEP CAR      3
3   MOPED/SCOOTER                                      4
4   MOTOR CYCLE                                        4
5                                   AUTO RICKSHAW      6
6   LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON             6
7                                           TEMPO      6
8   LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON             7
9                      PRIVATE MOTOR CAR/JEEP CAR      8
10                                          TEMPO      8
11  MOPED/SCOOTER                                     10
12                                  AUTO RICKSHAW     10
13             PUBLIC MOTOR CAR MORE THAN 16 SEAT     11
14                   PUBLIC MOTOR CAR 1 TO 6 SEAT     12
15                  PUBLIC MOTOR CAR 7 TO 15 SEAT     12
16  LOADING TRUCK/TEMPO/TRACTOR UPTO 2 TON            12
17  MOPED/SCOOTER                                      1
18  LOADING TRUCK/TEMPO/TRACTOR 4 TO 8 TON             1
19  MOPED/SCOOTER                                      2
20  MOTOR CYCLE                                        2
21                     PRIVATE MOTOR CAR/JEEP CAR      2

In [76]:
incorrectData.filter(like='n')

                                      Description  Month  Count    Amount
0                    "MOTOR CYCLE"                     8    1.0     144.0
1   MOTOR CYCLE                                        3    1.0      27.0
2                      PRIVATE MOTOR CAR/JEEP CAR      3    2.0     144.0
3   MOPED/SCOOTER                                      4    NaN   21230.0
4   MOTOR CYCLE                                        4  105.0    7022.0
5                                   AUTO RICKSHAW      6    5.0    1294.0
6   LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON             6    3.0    1050.0
7                                           TEMPO      6    3.0     468.0
8   LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON             7    1.0     180.0
9                      PRIVATE MOTOR CAR/JEEP CAR      8   56.0    5530.0
10                                          TEMPO      8    2.0     108.0
11  MOPED/SCOOTER                                     10  750.0  114669.0
12                                  AUTO RICKSHAW     10    2.0     318.0
13             PUBLIC MOTOR CAR MORE THAN 16 SEAT     11    1.0     360.0
14                   PUBLIC MOTOR CAR 1 TO 6 SEAT     12    9.0    3348.0
15                  PUBLIC MOTOR CAR 7 TO 15 SEAT     12    1.0     744.0
16  LOADING TRUCK/TEMPO/TRACTOR UPTO 2 TON            12    1.0     684.0
17  MOPED/SCOOTER                                      1  309.0   39575.3
18  LOADING TRUCK/TEMPO/TRACTOR 4 TO 8 TON             1    3.0     780.0
19  MOPED/SCOOTER                                      2  140.0   15983.0
20  MOTOR CYCLE                                        2   38.0    4099.0
21                     PRIVATE MOTOR CAR/JEEP CAR      2   35.0    8185.0

In [78]:
incorrectData.loc[incorrectData['Description'].str.contains('CAR')]

,CityName,VehicleTypeId,Description,Year,Month,Count,Amount
2,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,NaN,3,2.0,144.0
9,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1997.0,8,56.0,5530.0
13,Surat,7,PUBLIC MOTOR CAR MORE THAN 16 SEAT,1997.0,11,1.0,360.0
14,Surat,5,PUBLIC MOTOR CAR 1 TO 6 SEAT,1997.0,12,9.0,3348.0
15,Surat,6,PUBLIC MOTOR CAR 7 TO 15 SEAT,1997.0,12,1.0,744.0
21,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1998.0,2,35.0,8185.0