In [9]:
import pandas as pd
import numpy as np

In [51]:
UserData = pd.read_csv('users.csv')

In [53]:
UserData.head()

      Name  Age  Markes  Score Gender
0    Rahul   11      65     10      M
1  Deepika   16      60     11      F
2    Rakhi   45      30     16      F
3    Raman   54      66     14      M
4   Ranjot   65      69     13      M

In [55]:
user_data = pd.DataFrame(UserData)

In [57]:
user_data

      Name  Age  Markes  Score Gender
0    Rahul   11      65     10      M
1  Deepika   16      60     11      F
2    Rakhi   45      30     16      F
3    Raman   54      66     14      M
4   Ranjot   65      69     13      M

In [59]:
print(user_data.columns)

Index(['Name', 'Age', 'Markes', 'Score', 'Gender'], dtype='object')

In [61]:
user_data['num_Gender'] = np.where(user_data.Gender == 'M',0,1)

In [63]:
user_data

      Name  Age  Markes  Score Gender  num_Gender
0    Rahul   11      65     10      M           0
1  Deepika   16      60     11      F           1
2    Rakhi   45      30     16      F           1
3    Raman   54      66     14      M           0
4   Ranjot   65      69     13      M           0