In [1]:
import pandas as pd

In [3]:
vt = pd.read_csv("vehicle_taxes.csv")

In [5]:
vt.head()

,CityName,VehicleTypeId,Description,Year,Month,Count,Amount
0,Surat,1,MOPED/SCOOTER,1989,4,2,293.0
1,Surat,1,MOPED/SCOOTER,1989,7,1,162.0
2,Surat,1,MOPED/SCOOTER,1989,8,1,144.0
3,Surat,1,MOPED/SCOOTER,1989,10,1,144.0
4,Surat,5,LOADING TRUCK/TEMPO/TRACTOR 2 TO $ TON,1989,12,1,216.0

In [ ]:
## Check Columns type

In [7]:
type(vt.Description)

pandas.core.series.Series

In [ ]:
#Create Series

In [9]:
l= [1,2,3,4,5,6]
type(l)

list

In [36]:
ser = pd.Series(l)

In [ ]:
# index value

In [38]:
print(ser)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
#Changes defoult Index

In [40]:
Ser1 = pd.Series(l, index=['a','b','c', 'd','e','f'])
print(Ser1)

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [ ]:
#create Series from Dict

In [42]:
dictDemo = {'A':10, 'B':12, 'C':13}
ser3 = pd.Series(dictDemo)
print(ser3)

A    10
B    12
C    13
dtype: int64

In [44]:
ser

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [52]:
ser5 = ser._append(pd.Series([5,6]))
print(ser5)

0    1
1    2
2    3
3    4
4    5
5    6
0    5
1    6
dtype: int64

In [54]:
ser5.drop(4)

0    1
1    2
2    3
3    4
5    6
0    5
1    6
dtype: int64

In [56]:
ser5.drop(0)

1    2
2    3
3    4
4    5
5    6
1    6
dtype: int64

In [58]:
ser5.drop([1,2,3])

0    1
4    5
5    6
0    5
dtype: int64

In [60]:
ser

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [62]:
ser.loc[1:4]

1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
#Binary operations on Series

In [66]:
s1 = pd.Series([1,2,3,4,5])

In [70]:
s2 = pd.Series([6,7,8,9,10])
s3=s1+s2
print(s3)

0     7
1     9
2    11
3    13
4    15
dtype: int64

In [94]:
##DataFram Demo

In [118]:
data = {
    'Name': ['Anuj', 'Rahul', 'Anil', 'Vikram', 'Deepak', 'Surbhi'],
       'Age' : [18,22,34,35,30,29,27,31],
       'Gender': ['M','M','M','M','M','F']
      }

In [126]:

data = {
    'Name': ["Ajay", "Rahu", "Aman", "Anik"],
    'Gender': ['M', 'F', 'M', 'F'],
    'Age': [10.5, 20.3, 30.8, 40.2]
}

# Convert dictionary to DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

   Name Gender   Age
0  Ajay      M  10.5
1  Rahu      F  20.3
2  Aman      M  30.8
3  Anik      F  40.2

In [132]:
df1 = pd.DataFrame(data, index=['ONE', 'TWO', 'THREE', 'FOUR'])
df1

       Name Gender   Age
ONE    Ajay      M  10.5
TWO    Rahu      F  20.3
THREE  Aman      M  30.8
FOUR   Anik      F  40.2

In [134]:
df1.Name

ONE      Ajay
TWO      Rahu
THREE    Aman
FOUR     Anik
Name: Name, dtype: object

In [136]:
df1['Name']

ONE      Ajay
TWO      Rahu
THREE    Aman
FOUR     Anik
Name: Name, dtype: object

In [138]:
df1.head()

       Name Gender   Age
ONE    Ajay      M  10.5
TWO    Rahu      F  20.3
THREE  Aman      M  30.8
FOUR   Anik      F  40.2

In [ ]:
# Head function show 5 rows

In [140]:
df1.head(2)

     Name Gender   Age
ONE  Ajay      M  10.5
TWO  Rahu      F  20.3