In [20]:
import pandas as pd

In [22]:
vehicleTaxData = pd.read_csv("vehicleTax.csv")

In [24]:
vehicleTaxData.head()

,CityName,VehicleTypeId,Description,Year,Month,Count,Amount
0,Surat,1,MOPED/SCOOTER,1989,8,1,144.0
1,Surat,2,MOTOR CYCLE,1994,3,1,27.0
2,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1997,3,2,144.0
3,Surat,1,MOPED/SCOOTER,1997,4,312,21230.0
4,Surat,2,MOTOR CYCLE,1997,4,105,7022.0

In [26]:
vehicleTaxData.tail()

,CityName,VehicleTypeId,Description,Year,Month,Count,Amount
3821,Surat,37,CNG Fitted Four Wheeler,2025,2,510,7883994.0
3822,Surat,23,FORKLIFT,2025,3,1,43750.0
3823,Surat,34,E - Three Wheeler,2025,3,8,22502.0
3824,Surat,38,CNG Fitted Goods Vehiclers/more than three Whe...,2025,3,17,114674.0
3825,Surat,44,CNG FITTED MOTOR CYCLE,2025,3,29,57521.0

In [28]:
data = pd.DataFrame(vehicleTaxData)

In [30]:
data.head()

,CityName,VehicleTypeId,Description,Year,Month,Count,Amount
0,Surat,1,MOPED/SCOOTER,1989,8,1,144.0
1,Surat,2,MOTOR CYCLE,1994,3,1,27.0
2,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1997,3,2,144.0
3,Surat,1,MOPED/SCOOTER,1997,4,312,21230.0
4,Surat,2,MOTOR CYCLE,1997,4,105,7022.0

In [32]:
data.head(2)

,CityName,VehicleTypeId,Description,Year,Month,Count,Amount
0,Surat,1,MOPED/SCOOTER,1989,8,1,144.0
1,Surat,2,MOTOR CYCLE,1994,3,1,27.0

In [34]:
data.tail(1)

,CityName,VehicleTypeId,Description,Year,Month,Count,Amount
3825,Surat,44,CNG FITTED MOTOR CYCLE,2025,3,29,57521.0

In [36]:
data.head(100)

,CityName,VehicleTypeId,Description,Year,Month,Count,Amount
0,Surat,1,MOPED/SCOOTER,1989,8,1,144.0
1,Surat,2,MOTOR CYCLE,1994,3,1,27.0
2,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1997,3,2,144.0
3,Surat,1,MOPED/SCOOTER,1997,4,312,21230.0
4,Surat,2,MOTOR CYCLE,1997,4,105,7022.0
...,...,...,...,...,...,...,...
95,Surat,12,TRAILER UPTO 2 TON,2002,9,1,432.0
96,Surat,1,MOPED/SCOOTER,2002,10,32,3156.0
97,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,2002,11,11,1152.0
98,Surat,9,LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON,2002,11,1,72.0
99,Surat,1,MOPED/SCOOTER,2002,12,14,867.0

In [42]:
data['VehicleTypeId']

21

In [44]:
data[['VehicleTypeId', 'CityName']]

      VehicleTypeId CityName
0                 1    Surat
1                 2    Surat
2                 4    Surat
3                 1    Surat
4                 2    Surat
...             ...      ...
3821             37    Surat
3822             23    Surat
3823             34    Surat
3824             38    Surat
3825             44    Surat

[3826 rows x 2 columns]

In [46]:
data.columns

Index(['CityName', 'VehicleTypeId', 'Description', 'Year', 'Month', 'Count',
       'Amount'],
      dtype='object')

In [48]:
data.index

RangeIndex(start=0, stop=3826, step=1)

In [50]:
data.shape

(3826, 7)

In [52]:
data.size

26782

In [54]:
data.Description

0           MOPED/SCOOTER
1           MOTOR CYCLE
2                              PRIVATE MOTOR CAR/JEEP CAR
3           MOPED/SCOOTER
4           MOTOR CYCLE
                              ...
3821                              CNG Fitted Four Wheeler
3822                                             FORKLIFT
3823                                    E - Three Wheeler
3824    CNG Fitted Goods Vehiclers/more than three Whe...
3825                               CNG FITTED MOTOR CYCLE
Name: Description, Length: 3826, dtype: object

In [56]:
data.CityName

0       Surat
1       Surat
2       Surat
3       Surat
4       Surat
        ...
3821    Surat
3822    Surat
3823    Surat
3824    Surat
3825    Surat
Name: CityName, Length: 3826, dtype: object

In [58]:
data.Year

0       1989
1       1994
2       1997
3       1997
4       1997
        ...
3821    2025
3822    2025
3823    2025
3824    2025
3825    2025
Name: Year, Length: 3826, dtype: int64

In [60]:
data.empty

False

In [62]:
data.values

array([['Surat', 1, 'MOPED/SCOOTER                                ', ...,
        8, 1, 144.0],
       ['Surat', 2, 'MOTOR CYCLE                                  ', ...,
        3, 1, 27.0],
       ['Surat', 4, 'PRIVATE MOTOR CAR/JEEP CAR', ..., 3, 2, 144.0],
       ...,
       ['Surat', 34, 'E - Three Wheeler', ..., 3, 8, 22502.0],
       ['Surat', 38,
        'CNG Fitted Goods Vehiclers/more than three Wheeler', ..., 3, 17,
        114674.0],
       ['Surat', 44, 'CNG FITTED MOTOR CYCLE', ..., 3, 29, 57521.0]],
      dtype=object)

In [66]:
data.axes

[RangeIndex(start=0, stop=3826, step=1),
 Index(['CityName', 'VehicleTypeId', 'Description', 'Year', 'Month', 'Count',
        'Amount'],
       dtype='object')]

In [68]:
data.dtypes

CityName          object
VehicleTypeId      int64
Description       object
Year               int64
Month              int64
Count              int64
Amount           float64
dtype: object

In [70]:
data.loc[2:10,]

,CityName,VehicleTypeId,Description,Year,Month,Count,Amount
2,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1997,3,2,144.0
3,Surat,1,MOPED/SCOOTER,1997,4,312,21230.0
4,Surat,2,MOTOR CYCLE,1997,4,105,7022.0
5,Surat,3,AUTO RICKSHAW,1997,6,5,1294.0
6,Surat,9,LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON,1997,6,3,1050.0
7,Surat,21,TEMPO,1997,6,3,468.0
8,Surat,9,LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON,1997,7,1,180.0
9,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1997,8,56,5530.0
10,Surat,21,TEMPO,1997,8,2,108.0

In [72]:
data.loc[2:10,['VehicleTypeId', 'Description']]

    VehicleTypeId                                    Description
2               4                     PRIVATE MOTOR CAR/JEEP CAR
3               1  MOPED/SCOOTER
4               2  MOTOR CYCLE
5               3                                  AUTO RICKSHAW
6               9  LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON
7              21                                          TEMPO
8               9  LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON
9               4                     PRIVATE MOTOR CAR/JEEP CAR
10             21                                          TEMPO

In [74]:
data.describe()

       VehicleTypeId         Year        Month         Count        Amount
count    3826.000000  3826.000000  3826.000000   3826.000000  3.826000e+03
mean       11.739676  2013.456090     6.404339    654.067956  2.990401e+06
std        10.305868     8.263616     3.495337   1562.059125  1.077294e+07
min         1.000000  1989.000000     1.000000      1.000000  0.000000e+00
25%         3.000000  2008.000000     3.000000      2.000000  9.561250e+03
50%         9.000000  2015.000000     6.000000     16.000000  9.495800e+04
75%        19.000000  2021.000000     9.000000    208.000000  8.994132e+05
max        44.000000  2025.000000    12.000000  10143.000000  1.309929e+08

In [78]:
data.Amount.describe()

count    3.826000e+03
mean     2.990401e+06
std      1.077294e+07
min      0.000000e+00
25%      9.561250e+03
50%      9.495800e+04
75%      8.994132e+05
max      1.309929e+08
Name: Amount, dtype: float64

In [80]:
data.Description.describe()

count                                              3826
unique                                               43
top       MOTOR CYCLE
freq                                                340
Name: Description, dtype: object

In [82]:
copyData = data.copy()

In [84]:
copyData.head()

,CityName,VehicleTypeId,Description,Year,Month,Count,Amount
0,Surat,1,MOPED/SCOOTER,1989,8,1,144.0
1,Surat,2,MOTOR CYCLE,1994,3,1,27.0
2,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1997,3,2,144.0
3,Surat,1,MOPED/SCOOTER,1997,4,312,21230.0
4,Surat,2,MOTOR CYCLE,1997,4,105,7022.0

In [86]:
copy = data.drop(columns = ['CityName', 'Description'])

In [88]:
copy.head()

   VehicleTypeId  Year  Month  Count   Amount
0              1  1989      8      1    144.0
1              2  1994      3      1     27.0
2              4  1997      3      2    144.0
3              1  1997      4    312  21230.0
4              2  1997      4    105   7022.0

In [90]:
import numpy as np

In [134]:
data.Amount.size

3826

In [136]:
value = np.arange(0,3826)

In [120]:
value

array([   0,    1,    2, ..., 3823, 3824, 3825])

In [138]:
data.head()

,CityName,VehicleTypeId,Description,Year,Month,Count,Amount
0,Surat,1,MOPED/SCOOTER,1989,8,1,0
1,Surat,2,MOTOR CYCLE,1994,3,1,1
2,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1997,3,2,2
3,Surat,1,MOPED/SCOOTER,1997,4,312,3
4,Surat,2,MOTOR CYCLE,1997,4,105,4

In [122]:

data.size

26782

In [140]:
data['Amount'] = value

In [142]:
data.head()

,CityName,VehicleTypeId,Description,Year,Month,Count,Amount
0,Surat,1,MOPED/SCOOTER,1989,8,1,0
1,Surat,2,MOTOR CYCLE,1994,3,1,1
2,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1997,3,2,2
3,Surat,1,MOPED/SCOOTER,1997,4,312,3
4,Surat,2,MOTOR CYCLE,1997,4,105,4

In [130]:
data.Amount.size

3826

In [144]:
rows = data.iloc[0:4]

In [146]:
rows

,CityName,VehicleTypeId,Description,Year,Month,Count,Amount
0,Surat,1,MOPED/SCOOTER,1989,8,1,0
1,Surat,2,MOTOR CYCLE,1994,3,1,1
2,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1997,3,2,2
3,Surat,1,MOPED/SCOOTER,1997,4,312,3

In [148]:
newRow = data.iloc[0:10]

In [150]:
newRow

,CityName,VehicleTypeId,Description,Year,Month,Count,Amount
0,Surat,1,MOPED/SCOOTER,1989,8,1,0
1,Surat,2,MOTOR CYCLE,1994,3,1,1
2,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1997,3,2,2
3,Surat,1,MOPED/SCOOTER,1997,4,312,3
4,Surat,2,MOTOR CYCLE,1997,4,105,4
5,Surat,3,AUTO RICKSHAW,1997,6,5,5
6,Surat,9,LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON,1997,6,3,6
7,Surat,21,TEMPO,1997,6,3,7
8,Surat,9,LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON,1997,7,1,8
9,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1997,8,56,9

In [154]:
duplicatRow = rows._append(newRow)

In [156]:
duplicatRow.head(10)

,CityName,VehicleTypeId,Description,Year,Month,Count,Amount
0,Surat,1,MOPED/SCOOTER,1989,8,1,0
1,Surat,2,MOTOR CYCLE,1994,3,1,1
2,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1997,3,2,2
3,Surat,1,MOPED/SCOOTER,1997,4,312,3
0,Surat,1,MOPED/SCOOTER,1989,8,1,0
1,Surat,2,MOTOR CYCLE,1994,3,1,1
2,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1997,3,2,2
3,Surat,1,MOPED/SCOOTER,1997,4,312,3
4,Surat,2,MOTOR CYCLE,1997,4,105,4
5,Surat,3,AUTO RICKSHAW,1997,6,5,5

In [160]:
duplicatRow.drop_duplicates().head(10)

,CityName,VehicleTypeId,Description,Year,Month,Count,Amount
0,Surat,1,MOPED/SCOOTER,1989,8,1,0
1,Surat,2,MOTOR CYCLE,1994,3,1,1
2,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1997,3,2,2
3,Surat,1,MOPED/SCOOTER,1997,4,312,3
4,Surat,2,MOTOR CYCLE,1997,4,105,4
5,Surat,3,AUTO RICKSHAW,1997,6,5,5
6,Surat,9,LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON,1997,6,3,6
7,Surat,21,TEMPO,1997,6,3,7
8,Surat,9,LOADING TRUCK/TEMPO/TRACTOR 2 TO 4 TON,1997,7,1,8
9,Surat,4,PRIVATE MOTOR CAR/JEEP CAR,1997,8,56,9

In [162]:
# Setting column name
# Data consistency check
# On Hot Encoding

In [164]:
# Data Summurasion technique